services:
  database:
    image: mysql:8.0
    container_name: catalogue_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: democatalogue
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3307:3306"
    volumes:
      - database_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: myadmin
    restart: unless-stopped
    depends_on:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: symfony
      PMA_PASSWORD: symfony
    ports:
      - "8081:80"

volumes:
  database_data:
